/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type CompanyStage =
  | "Idea Stage"
  | "MVP"
  | "Pre-Seed"
  | "Seed"
  | "Series A"
  | "Series B"
  | "Growth"
  | "Enterprise";

export type ScenarioKind =
  | "hiring-fast"
  | "ignored-users"
  | "scaled-early"
  | "unwanted-features"
  | "pricing-anchor"
  | "wrong-investor"
  | "technical-rewrite"
  | "market-positioning"
  | "compliance-delay"
  | "enterprise-distraction";

export interface StoryTemplate {
  category: string;
  domain: string;
  businessModel: string;
  technicalMaturity: string;
  scenario: ScenarioKind;
  title: string;
  summary: string;
  decisionAction: string;
  whyCorrectThen: string;
  emotionalFactors: string;
  assumption: string;
  negative: string;
  positive: string;
  surprise: string;
  neverRepeat: string;
  lesson: string;
  topics: string[];
}

export const stages: CompanyStage[] = [
  "Idea Stage",
  "MVP",
  "Pre-Seed",
  "Seed",
  "Series A",
  "Series B",
  "Growth",
  "Enterprise",
];

export const fundingProfiles = [
  "bootstrapped from customer revenue",
  "$120k angel round",
  "$650k pre-seed",
  "$2.4M seed round",
  "$8M Series A",
  "$21M Series B",
  "profitable, no outside capital",
  "strategic corporate pilot funding",
];

export const geographies = [
  "Austin",
  "Bengaluru",
  "Berlin",
  "Toronto",
  "Nairobi",
  "Sao Paulo",
  "Singapore",
  "London",
  "Chicago",
  "Tel Aviv",
  "Stockholm",
  "Melbourne",
];

export const timestamps = [
  "2 hours ago",
  "Yesterday",
  "3 days ago",
  "Last week",
  "2 weeks ago",
  "1 month ago",
];

export const templates: StoryTemplate[] = [
  {
    category: "Startup",
    domain: "SaaS",
    businessModel: "seat-based B2B SaaS",
    technicalMaturity: "single-tenant Rails app with a small React surface",
    scenario: "scaled-early",
    title: "We split the product into services before we had one repeatable customer",
    summary: "Our architecture looked grown-up, but our sales calls were still teaching us what the product should be.",
    decisionAction: "I moved three engineers onto a microservices migration because I believed enterprise buyers would ask about scale before signing.",
    whyCorrectThen: "Two prospects had asked about uptime, and I mistook procurement language for an urgent technical requirement.",
    emotionalFactors: "I wanted the company to feel more mature than it was and liked telling investors we were enterprise-ready.",
    assumption: "Enterprise readiness would unlock revenue faster than narrowing the workflow.",
    negative: "We lost two release cycles, shipped no visible customer value, and created paging paths nobody on the team fully owned.",
    positive: "The migration forced us to document the oldest billing flows and expose tests we should have written earlier.",
    surprise: "The first signed customers cared more about CSV exports and onboarding emails than service boundaries.",
    neverRepeat: "I will never let imagined scale outrank verified user pain again.",
    lesson: "Architecture should follow repeated demand, not founder anxiety.",
    topics: ["Microservices", "Enterprise Sales", "Product-Market Fit"],
  },
  {
    category: "Product",
    domain: "Consumer Apps",
    businessModel: "freemium mobile subscription",
    technicalMaturity: "native iOS app with a thin analytics layer",
    scenario: "ignored-users",
    title: "I ignored the quiet power users because a louder segment felt more exciting",
    summary: "The retention was hiding in boring workflows, and I nearly optimized it away.",
    decisionAction: "We redesigned the home screen around social sharing instead of the private habit tracker our daily users opened every morning.",
    whyCorrectThen: "Screenshots from competitors made social loops look like the only path to growth.",
    emotionalFactors: "I was tired of explaining a plain utility app and wanted a product that sounded more viral.",
    assumption: "More public activity would create more acquisition without harming the original use case.",
    negative: "Week-four retention dropped, support tickets spiked, and the most loyal users said the app no longer felt like theirs.",
    positive: "A small rollback interview sprint gave us the clearest segmentation we had ever had.",
    surprise: "Users who never emailed support were the ones anchoring paid conversion.",
    neverRepeat: "I will never equate silence with satisfaction or irrelevance.",
    lesson: "The users who complain least can be the ones carrying the business.",
    topics: ["Retention", "User Research", "Consumer Product"],
  },
  {
    category: "Engineering",
    domain: "DevTools",
    businessModel: "usage-based developer platform",
    technicalMaturity: "Kubernetes-heavy backend with early observability gaps",
    scenario: "technical-rewrite",
    title: "Our rewrite made the demo faster and the company slower",
    summary: "I treated a working but awkward codebase like a reputation problem instead of a customer problem.",
    decisionAction: "We paused feature work to rewrite the job runner in Go after a senior candidate criticized the Node service.",
    whyCorrectThen: "The old runner was hard to reason about, and the team believed a rewrite would make future hiring and reliability easier.",
    emotionalFactors: "I was embarrassed by old decisions and wanted the engineering culture to look sharper.",
    assumption: "A cleaner internal system would quickly pay back the pause in roadmap velocity.",
    negative: "The rewrite took eleven weeks, recreated old edge cases, and delayed the integrations customers had already budgeted around.",
    positive: "We finally added tracing and learned which jobs actually needed performance work.",
    surprise: "The original bottleneck was a third-party API limit, not our language choice.",
    neverRepeat: "I will never approve a rewrite without a customer-facing success metric.",
    lesson: "Rewrite only the part that blocks the business, and prove the blockage first.",
    topics: ["Technical Debt", "Rewrites", "Observability"],
  },
  {
    category: "AI",
    domain: "AI",
    businessModel: "API metering plus enterprise contracts",
    technicalMaturity: "LLM orchestration layer with manual evaluation",
    scenario: "unwanted-features",
    title: "We built model controls for buyers who had not trusted the output yet",
    summary: "The dashboard looked sophisticated while the core answer quality still felt uneven.",
    decisionAction: "I prioritized advanced prompt controls and model routing instead of a boring evaluation workflow for the first use case.",
    whyCorrectThen: "Technical champions loved the roadmap and kept asking whether they could tune every layer.",
    emotionalFactors: "The team wanted to be seen as a serious AI infrastructure company, not a narrow workflow tool.",
    assumption: "More configurability would make skeptical teams feel safer adopting us.",
    negative: "Trials became harder to onboard, and buyers blamed themselves when output quality varied.",
    positive: "The unused controls showed us which parts of the system customers did not want to own.",
    surprise: "The winning feature was a weekly failure review email, not another knob.",
    neverRepeat: "I will never give customers complexity before I earn their trust.",
    lesson: "In AI products, confidence often beats configurability.",
    topics: ["AI Evaluation", "Onboarding", "Feature Scope"],
  },
  {
    category: "Marketing",
    domain: "E-commerce",
    businessModel: "direct-to-consumer margin",
    technicalMaturity: "Shopify stack with lightweight attribution",
    scenario: "market-positioning",
    title: "We copied a competitor's positioning and attracted the wrong customers",
    summary: "The ads converted, but the buyers wanted a cheaper product than the one we could profitably sell.",
    decisionAction: "We shifted our launch campaign toward discount-driven comparisons because a larger brand was winning with that language.",
    whyCorrectThen: "The early click-through rate was almost double our original education-led campaign.",
    emotionalFactors: "I panicked when our first launch week was quiet and wanted a visible win.",
    assumption: "If the top of funnel got cheaper, the unit economics would work themselves out.",
    negative: "Refunds climbed, support became combative, and our contribution margin was negative on the best-performing campaign.",
    positive: "The campaign data forced us to write a sharper premium buyer profile.",
    surprise: "Customers who paid full price had shorter support threads and higher repeat purchase rates.",
    neverRepeat: "I will never borrow a competitor's promise without borrowing their cost structure too.",
    lesson: "Positioning that wins clicks can still damage the business.",
    topics: ["Positioning", "Paid Acquisition", "Unit Economics"],
  },
  {
    category: "Sales",
    domain: "Enterprise Software",
    businessModel: "annual enterprise contracts",
    technicalMaturity: "mature web app with custom implementation scripts",
    scenario: "enterprise-distraction",
    title: "One huge logo pulled our roadmap away from the customers already renewing",
    summary: "The deal looked company-making until we counted what it did to the rest of the pipeline.",
    decisionAction: "I accepted a custom security and workflow package for a marquee enterprise prospect before the contract was signed.",
    whyCorrectThen: "The logo would have changed our fundraising story, and the champion sounded committed.",
    emotionalFactors: "I wanted the team to feel we had finally broken into the top tier.",
    assumption: "A flagship customer would create proof that smaller customers could not provide.",
    negative: "The prospect delayed procurement twice, and we missed renewal improvements for twenty-three existing accounts.",
    positive: "The security work later helped with two smaller regulated customers.",
    surprise: "Our best-fit customers did not need half of what the enterprise team demanded.",
    neverRepeat: "I will never let an unsigned enterprise roadmap become the company roadmap.",
    lesson: "A large prospect is not a strategy until the contract and opportunity cost are both real.",
    topics: ["Enterprise Sales", "Roadmap", "Procurement"],
  },
  {
    category: "Fundraising",
    domain: "FinTech",
    businessModel: "transaction fee plus compliance services",
    technicalMaturity: "audited backend with bank partner dependencies",
    scenario: "wrong-investor",
    title: "We chose the fastest term sheet and inherited the slowest board dynamic",
    summary: "The money arrived quickly, but every strategic conversation got heavier afterward.",
    decisionAction: "I accepted a seed offer from the investor who moved first instead of waiting for funds with deeper regulated-market experience.",
    whyCorrectThen: "Runway was down to four months, and speed felt like the responsible choice.",
    emotionalFactors: "I was exhausted from pitching and afraid the round would collapse if I negotiated.",
    assumption: "Capital was mostly interchangeable at seed stage as long as the valuation was fair.",
    negative: "Board meetings became generic growth lectures while our real blockers were bank reviews and compliance sequencing.",
    positive: "The round kept the team together and bought time to recover our partner pipeline.",
    surprise: "The most expensive part was not dilution; it was advice that pulled us toward the wrong milestones.",
    neverRepeat: "I will never evaluate money without evaluating the operating judgment attached to it.",
    lesson: "The right investor should reduce strategic noise, not add to it.",
    topics: ["Fundraising", "FinTech", "Board Management"],
  },
  {
    category: "Leadership",
    domain: "Healthcare",
    businessModel: "clinic SaaS with implementation fees",
    technicalMaturity: "HIPAA-oriented product with manual onboarding",
    scenario: "hiring-fast",
    title: "I hired ahead of clarity and turned ambiguity into payroll",
    summary: "The team got bigger before the operating system did.",
    decisionAction: "I hired three managers in one quarter because I thought structure would solve founder-led bottlenecks.",
    whyCorrectThen: "Everyone was overloaded, customers wanted faster implementations, and investors kept asking about leadership depth.",
    emotionalFactors: "I wanted to stop being the constraint and mistook headcount for relief.",
    assumption: "Experienced managers would create process while also absorbing execution pressure.",
    negative: "Roles overlapped, decision rights blurred, and the strongest individual contributors spent weeks explaining context.",
    positive: "One manager built the first reliable implementation checklist before we re-scoped the team.",
    surprise: "The missing piece was not management experience; it was written ownership.",
    neverRepeat: "I will never hire a role before I can write the decisions it owns.",
    lesson: "Hiring amplifies clarity or confusion. It does not create clarity by itself.",
    topics: ["Hiring", "Management", "Healthcare"],
  },
  {
    category: "Design",
    domain: "EdTech",
    businessModel: "school district licenses",
    technicalMaturity: "accessible web app with classroom analytics",
    scenario: "ignored-users",
    title: "We designed for administrators and made teachers do extra work",
    summary: "The buyer loved the dashboards, but the daily user quietly worked around us.",
    decisionAction: "We redesigned the product around district-level reporting instead of simplifying lesson setup for teachers.",
    whyCorrectThen: "Administrators controlled the budget and asked for stronger proof of usage.",
    emotionalFactors: "I wanted procurement calls to feel impressive and measurable.",
    assumption: "If administrators saw better analytics, teacher adoption would follow.",
    negative: "Teachers exported data into spreadsheets because our classroom flow added too many steps.",
    positive: "The reporting model later became useful once we fixed the input burden.",
    surprise: "District champions lost confidence when teachers stopped mentioning us unprompted.",
    neverRepeat: "I will never optimize the buyer's view by taxing the user's day.",
    lesson: "A dashboard is only as good as the workflow that feeds it.",
    topics: ["Design", "EdTech", "Buyer vs User"],
  },
  {
    category: "Career",
    domain: "Creator Economy",
    businessModel: "take-rate marketplace",
    technicalMaturity: "marketplace MVP with manual matching operations",
    scenario: "pricing-anchor",
    title: "My first pricing conversation anchored the whole marketplace too low",
    summary: "I wanted liquidity, so I taught the market to undervalue the supply.",
    decisionAction: "I set launch pricing around what our first demand-side partner said felt comfortable.",
    whyCorrectThen: "We needed transactions, and I believed low prices would reduce friction while we learned.",
    emotionalFactors: "As a first-time founder, I was relieved someone gave me a number at all.",
    assumption: "We could raise prices later after proving volume.",
    negative: "Creators compared every later offer to the original low anchor and churned when we tried to correct it.",
    positive: "The pricing mistake exposed which creators had real commercial pull.",
    surprise: "Demand did not value the marketplace more just because supply accepted less.",
    neverRepeat: "I will never let the least informed early buyer define market value.",
    lesson: "Early pricing is not temporary when it becomes the reference point.",
    topics: ["Pricing", "Marketplaces", "Creator Economy"],
  },
  {
    category: "Startup",
    domain: "ClimateTech",
    businessModel: "hardware-enabled carbon reporting",
    technicalMaturity: "sensor prototype with manual calibration",
    scenario: "compliance-delay",
    title: "We treated certification like paperwork and lost the selling season",
    summary: "The product worked in demos before it was trusted in procurement.",
    decisionAction: "I delayed third-party certification until after pilots because I wanted proof before spending scarce capital.",
    whyCorrectThen: "The lab quote felt expensive, and early customers said they were comfortable testing prototypes.",
    emotionalFactors: "I was protective of runway and overly proud of our field data.",
    assumption: "Successful pilots would make compliance review a formality.",
    negative: "Procurement teams paused after pilots, and a competitor with weaker data but stronger certification took the annual budget.",
    positive: "The pause forced us to build better calibration records and chain-of-custody documentation.",
    surprise: "Trust artifacts mattered as much as sensor accuracy in the buying process.",
    neverRepeat: "I will never separate product proof from procurement proof in regulated markets.",
    lesson: "In trust-heavy categories, compliance is part of the product.",
    topics: ["ClimateTech", "Compliance", "Procurement"],
  },
  {
    category: "Engineering",
    domain: "Cybersecurity",
    businessModel: "per-seat security monitoring",
    technicalMaturity: "event pipeline with partial alert automation",
    scenario: "scaled-early",
    title: "We optimized ingestion before fixing alert fatigue",
    summary: "Our pipeline handled more events, but customers still ignored the alerts that mattered.",
    decisionAction: "We invested in a high-throughput ingestion layer instead of pruning noisy detection rules.",
    whyCorrectThen: "A few pilots had large event volumes, and the engineering problem was concrete.",
    emotionalFactors: "Throughput felt like a clean win compared with messy customer interviews about false positives.",
    assumption: "More scalable infrastructure would make the product credible to security teams.",
    negative: "The product became faster at generating alerts analysts did not trust.",
    positive: "The new pipeline made later rule testing cheaper once we narrowed the taxonomy.",
    surprise: "Security leads judged us by the first five alerts, not by maximum events per second.",
    neverRepeat: "I will never scale a noisy signal before improving the signal.",
    lesson: "Performance is not value when the output is wrong.",
    topics: ["Cybersecurity", "Infrastructure", "Signal Quality"],
  },
  {
    category: "Product",
    domain: "Robotics",
    businessModel: "robotics-as-a-service",
    technicalMaturity: "field-tested robots with remote operator fallback",
    scenario: "unwanted-features",
    title: "We automated the impressive part and left the painful part manual",
    summary: "The demo wowed visitors, but operators still hated the daily exception queue.",
    decisionAction: "I prioritized autonomous navigation upgrades instead of the unglamorous exception handling console.",
    whyCorrectThen: "Navigation footage sold the vision and made investor updates feel tangible.",
    emotionalFactors: "I wanted the product to feel like robotics, not operations software.",
    assumption: "Better autonomy would naturally reduce the operator burden.",
    negative: "Operators spent the same number of hours resolving edge cases, only with less predictable timing.",
    positive: "The autonomy work reduced battery waste and gave us cleaner telemetry.",
    surprise: "Customers described the exception queue as the actual product experience.",
    neverRepeat: "I will never confuse the most photogenic feature with the most painful workflow.",
    lesson: "The part customers touch during failure often defines the product.",
    topics: ["Robotics", "Operations", "Product Scope"],
  },
  {
    category: "Sales",
    domain: "Logistics",
    businessModel: "per-shipment coordination fee",
    technicalMaturity: "workflow app integrated with carrier APIs",
    scenario: "market-positioning",
    title: "We sold ourselves as automation when customers needed accountability",
    summary: "The message sounded modern, but buyers were really paying to know who owned the exception.",
    decisionAction: "We positioned the product around automated routing instead of exception resolution and customer communication.",
    whyCorrectThen: "Automation tested well in cold email subject lines and investor decks.",
    emotionalFactors: "I wanted to distance us from sounding like a services-heavy logistics company.",
    assumption: "Buyers would value reduced manual work above all else.",
    negative: "Demos stalled when teams asked who handled damaged shipments, missed pickups, and late carrier updates.",
    positive: "The failed positioning led us to package a higher-margin managed workflow tier.",
    surprise: "The word automation made some operators worry they would lose control during exceptions.",
    neverRepeat: "I will never let a fashionable category label obscure the buyer's real fear.",
    lesson: "Position around the risk customers already feel, not the technology you want credit for.",
    topics: ["Logistics", "Sales Messaging", "Operations"],
  },
  {
    category: "Leadership",
    domain: "Manufacturing",
    businessModel: "factory analytics annual licenses",
    technicalMaturity: "edge connectors plus cloud reporting",
    scenario: "hiring-fast",
    title: "We opened a second office before the first team had a cadence",
    summary: "Expansion looked like momentum from the outside and fragmentation from the inside.",
    decisionAction: "I hired a remote implementation pod in another region before our deployment playbook was stable.",
    whyCorrectThen: "Customer demand was geographically spread out, and travel costs were wearing down the founding team.",
    emotionalFactors: "I wanted to prove we could scale beyond founder heroics.",
    assumption: "Local presence would compensate for process gaps.",
    negative: "The new pod invented its own templates, customers got inconsistent rollouts, and engineering support became chaotic.",
    positive: "Regional feedback eventually exposed localization needs we had underestimated.",
    surprise: "Distance magnified every undocumented decision.",
    neverRepeat: "I will never distribute a process before it exists.",
    lesson: "Operational scale starts with repeatability, not geography.",
    topics: ["Manufacturing", "Operations", "Team Design"],
  },
  {
    category: "Marketing",
    domain: "Gaming",
    businessModel: "free-to-play cosmetics",
    technicalMaturity: "Unity live-ops stack with event analytics",
    scenario: "ignored-users",
    title: "We chased streamers and neglected the players who stayed every night",
    summary: "Awareness rose, but the community rituals that retained players weakened.",
    decisionAction: "We spent launch budget on streamer campaigns instead of improving guild tools requested by our core players.",
    whyCorrectThen: "The spikes from influencer tests were obvious and easy to report.",
    emotionalFactors: "I wanted the launch to look big, and community work felt less measurable.",
    assumption: "New player volume would make up for weaker veteran engagement.",
    negative: "Day-one installs jumped, but day-thirty retention fell and guild leaders moved their groups to other games.",
    positive: "The churn interviews gave us a sharper understanding of social progression.",
    surprise: "A few guild leaders influenced more durable revenue than several expensive streams.",
    neverRepeat: "I will never spend for reach while starving the rituals that make people return.",
    lesson: "Growth campaigns cannot replace the social glue of a product.",
    topics: ["Gaming", "Community", "Retention"],
  },
  {
    category: "Fundraising",
    domain: "Agritech",
    businessModel: "seasonal SaaS plus field services",
    technicalMaturity: "mobile-first app with offline sync",
    scenario: "wrong-investor",
    title: "We raised on software multiples for a business with seasonal reality",
    summary: "The pitch was cleaner than the operating model, and that mismatch hurt every planning cycle.",
    decisionAction: "I framed the round as pure SaaS growth even though onboarding required field visits and seasonal adoption windows.",
    whyCorrectThen: "Software metrics got better valuation reactions, and I thought services would shrink quickly.",
    emotionalFactors: "I wanted the company to be judged like the startups I admired.",
    assumption: "Field operations were temporary scaffolding rather than part of the go-to-market system.",
    negative: "Investor expectations pushed us into off-season experiments that farmers did not have time to adopt.",
    positive: "The pressure forced us to measure service margins and build partner-led onboarding.",
    surprise: "Services were not a weakness once priced and scheduled honestly.",
    neverRepeat: "I will never raise against a story the operating model cannot support.",
    lesson: "Fundraising narratives should stretch ambition, not deny the business model.",
    topics: ["Agritech", "Fundraising", "Business Model"],
  },
  {
    category: "AI",
    domain: "DeepTech",
    businessModel: "research license plus milestone contracts",
    technicalMaturity: "prototype model with lab validation",
    scenario: "pricing-anchor",
    title: "We priced breakthrough research like a dashboard subscription",
    summary: "I made the product easier to buy and harder to respect.",
    decisionAction: "I anchored pricing to familiar SaaS seats instead of the economic value of faster experiments.",
    whyCorrectThen: "Procurement understood seats, and I wanted the first contracts to close without education.",
    emotionalFactors: "I was nervous about asking for value-based pricing before we had a famous customer.",
    assumption: "Low-friction pricing would speed adoption and we could move upmarket later.",
    negative: "Customers treated the product as a nice-to-have tool instead of a core research accelerator.",
    positive: "The low price created enough usage to quantify time saved per experiment.",
    surprise: "Scientists defended a higher renewal price once we showed cycle-time data.",
    neverRepeat: "I will never hide value behind a familiar pricing model.",
    lesson: "Pricing teaches customers how seriously to take the product.",
    topics: ["DeepTech", "Pricing", "Value Metrics"],
  },
  {
    category: "Design",
    domain: "Biotech",
    businessModel: "platform license with research services",
    technicalMaturity: "secure portal backed by manual lab workflows",
    scenario: "compliance-delay",
    title: "Our beautiful portal failed because legal review had no path through it",
    summary: "We polished the user experience and forgot the institutional experience.",
    decisionAction: "We launched the customer portal before designing the consent, audit, and legal review flows around it.",
    whyCorrectThen: "Researchers loved the prototype, and we wanted to reduce manual project updates quickly.",
    emotionalFactors: "I was proud that a biotech tool finally felt modern.",
    assumption: "If researchers adopted the portal, compliance stakeholders would adapt around it.",
    negative: "Two customers paused rollout because audit trails and consent exports were not ready.",
    positive: "The redesign produced a clearer shared workspace for scientists, legal, and operations.",
    surprise: "The slowest user in the process had veto power over the fastest interface.",
    neverRepeat: "I will never design only for the person excited to log in.",
    lesson: "In regulated products, every required reviewer is part of the user journey.",
    topics: ["Biotech", "Design", "Compliance"],
  },
];
